AWSTemplateFormatVersion: '2010-09-09'
Description: Stack for StaticSite
Parameters:
  SiteBucketName:
    Type: String
Resources:
  SiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        Ref: SiteBucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    DependsOn: SiteBucket
    Properties:
      Bucket:
        Ref: SiteBucketName
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:List*'
              - 's3:GetObject'
            Resource:
              - !Sub 'arn:aws:s3:::${SiteBucketName}/*'
              - !Sub 'arn:aws:s3:::${SiteBucketName}'
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:role/deploy-prod-aero'
            Action: 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${SiteBucketName}/*'
              - !Sub 'arn:aws:s3:::${SiteBucketName}'
Outputs:
  BucketName:
    Value: !Ref 'SiteBucket'
    Description: Name of S3 bucket to hold website content
